[workspace]
members = ["contracts/ecdsa-lock", "contracts/ecdsa-recover-lock"]
exclude = ["tests"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
