[package]
name = "ecdsa-lock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.14.0"
k256 = { version = "0.13.3", default-features = false, features = [
    "alloc",
    "ecdsa",
] }
